<?php

namespace AutoDialBundle\Repository;

/**
 * ActiveCallingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiveCallingRepository extends \Doctrine\ORM\EntityRepository
{
}
