<?php

namespace AutoDialBundle\Repository;

/**
 * CallDialHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallDialHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
