<?php

namespace AutoDialBundle\Repository;

/**
 * DialRuleArrayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DialRuleArrayRepository extends \Doctrine\ORM\EntityRepository
{
}
