<?php

namespace AutoDialBundle\Repository;

/**
 * DialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DialRepository extends \Doctrine\ORM\EntityRepository
{
}
