<?php

namespace AutoDialBundle\Repository;

/**
 * PhoneWavRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneWavRepository extends \Doctrine\ORM\EntityRepository
{
}
