<?php

namespace AutoDialBundle\Repository;

/**
 * UserSoundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSoundRepository extends \Doctrine\ORM\EntityRepository
{
}
